################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../.build/organizations/ordererOrganizations/orderer.aomd.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

        OrdererEndpoints:
            - orderer.aomd.com:9050

    - &EducationOrg1
        Name: EducationOrg1MSP
        ID: EducationOrg1MSP
        MSPDir: ../.build/organizations/educationOrganizations/educationOrg1.aomd.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('EducationOrg1MSP.admin', 'EducationOrg1MSP.peer', 'EducationOrg1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('EducationOrg1MSP.admin', 'EducationOrg1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('EducationOrg1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('EducationOrg1MSP.peer')"

    - &AwardOrg1
        Name: AwardOrg1MSP
        ID: AwardOrg1MSP
        MSPDir: ../.build/organizations/awardOrganizations/awardOrg1.aomd.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AwardOrg1MSP.admin', 'AwardOrg1MSP.peer', 'AwardOrg1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AwardOrg1MSP.admin', 'AwardOrg1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AwardOrg1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('AwardOrg1MSP.peer')"

    - &LicenseOrg1
        Name: LicenseOrg1MSP
        ID: LicenseOrg1MSP
        MSPDir: ../.build/organizations/licenseOrganizations/licenseOrg1.aomd.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('LicenseOrg1MSP.admin', 'LicenseOrg1MSP.peer', 'LicenseOrg1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('LicenseOrg1MSP.admin', 'LicenseOrg1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('LicenseOrg1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('LicenseOrg1MSP.peer')"

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer.aomd.com:9050
    EtcdRaft:
        Consenters:
        - Host: orderer.aomd.com
          Port: 9050
          ClientTLSCert: ../.build/organizations/ordererOrganizations/orderer.aomd.com/orderers/orderer.aomd.com/tls/server.crt
          ServerTLSCert: ../.build/organizations/ordererOrganizations/orderer.aomd.com/orderers/orderer.aomd.com/tls/server.crt

    BatchTimeout: 2s

    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:
    AOMD:
      <<: *ChannelDefaults
      Orderer: 
        <<: *OrdererDefaults
        Organizations:
            - *OrdererOrg
        Capabilities:
            - *OrdererCapabilities
      Consortiums:
          EducationConsortium:
              Organizations:
                  - *EducationOrg1 
          AwardConsortium:
              Organizations:
                  - *AwardOrg1
          LicenseConsortium:
              Organizations:
                  - *LicenseOrg1

    EducationChannel:
        Consortium: EducationConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *EducationOrg1
            Capabilities:
                <<: *ApplicationCapabilities
    
    AwardChannel:
        Consortium: AwardConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *AwardOrg1
            Capabilities:
                <<: *ApplicationCapabilities
    
    LicenseChannel:
        Consortium: LicenseConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *LicenseOrg1
            Capabilities:
                <<: *ApplicationCapabilities
